---
- hosts: wiki
  remote_user: root
  tasks:
      - name: ensure that php5 is at the latest versions
        apt: name={{ item }} state=latest
        with-items:
            - php5-cgi
            - php5-gd
      - name: ensure that dokuwiki is at the latest version
        apt: name=dokuwiki state=latest
        notify:
            - restart nginx
  roles:
      - role: nginx
        configuration_file: 'templates/dokuwiki-nginx.conf'
        dest: 'dokuwiki'
