---
- name: upload nginx proxy configuration
  template:
      src: site_config.j2
      dest: "/etc/nginx/sites-available/{{ config_name }}"
  notify: restart nginx
- name: disable nginx default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: enable nginx proxy configuration
  file:
      src: "/etc/nginx/sites-available/{{ config_name }}"
      dest: "/etc/nginx/sites-enabled/{{ config_name }}"
      state: link
  notify: restart nginx
